// Import the function that returns a copy of the fish array
import { getFish } from './database.mjs';

const allFish = getFish();

// Import the FishList function from the correct module
import { FishList } from './fishList.mjs';

// Select the element where you want to display the fish
const fishParentHTMLElement = document.querySelector('#fish');

// Populate the selected element with the HTML generated by the FishList function
fishParentHTMLElement.innerHTML = FishList();

// Import the function that returns a copy of the tips array
import { getTips } from './database.mjs';

const allTips = getTips();

// Import the TipList function from the correct module
import { TipList } from './tipList.mjs';
// Select the element where you want to display the tips
const tipParentHTMLElement = document.querySelector('#tips');

// Populate the selected element with the HTML generated by the TipList function
tipParentHTMLElement.innerHTML = TipList();

//locations

import { LocationList } from './locationsList.mjs';
const locationParentHTMLElement =document.querySelector('#locations');

locationParentHTMLElement.innerHTML = LocationList